<a href="https://colab.research.google.com/github/Shubhamprdd/python-learning/blob/main/Numpy101.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
b = np.array([0, 0.5, 1 ,1.5, 2])

In [4]:
a[0], a[1]

(1, 2)

In [5]:
a[0:3]

array([1, 2, 3])

In [10]:
a[::2]

array([1, 3])

In [11]:
#Square Matrix
a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

In [12]:
a[1]

array([4, 5, 6])

In [13]:
a[0,:]

array([1, 2, 3])

In [14]:
a[:3]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
a[::2] #every second number

array([[1, 2, 3],
       [7, 8, 9]])

In [18]:
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [19]:
# alter
a[2] = 99

In [20]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [99, 99, 99]])

In [22]:
a[2] = np.array([7,8,9])

In [3]:
b = np.arange(5)

In [4]:
b

array([0, 1, 2, 3, 4])

In [5]:
b * 10

array([ 0, 10, 20, 30, 40])

In [6]:
b <2

array([ True,  True, False, False, False])